name: BuildMserviceA

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'mserviceA/**'
  push:
    branches: [ "main" ]
    paths:
      - 'mserviceA/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Pull test image (JHipster)
        run: docker pull testcontainersofficial/ryuk:0.3.0

      - name: build mserviceA
        run: ./mvnw clean package verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        working-directory: mserviceA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_MSERVICEA_TOKEN }}
